version: 1
accounts:
  - name: operator
    coins: ["1000token"]
  - name: validator
    coins: ["1000token", "100000000stake"]
  - name: user1
    coins: ["1000token"]
  - name: user2
    coins: ["1000token"]
validator:
  name: validator
  staked: "100000000stake"
